### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by Nidev-lab** [ruizemanuelm/proyectoFinal#59]
## Proceso

1. Ingrese a la pagina.
2. Me registre con un usuario nuevo.

## Resultado esperado

• Que al ingresar poder hacerlo como un usuario normal .

## Resultado actual

• Al registrar un nuevo usuario, el mismo se registra como usuario admin y al iniciar sesion tiene todo los permisos de administrador.

## Posible solucion

• Una posible solucion seria designar a un usuario admin y que ese usuario designe a los nuevos usuarios registrado como usuarios normales o admin.

## Captura

![image](https://github.com/ruizemanuelm/proyectoFinal/assets/53904695/742f94d8-45f1-468f-916f-c767b6f11878)
![image](https://github.com/ruizemanuelm/proyectoFinal/assets/53904695/1a48a296-7531-4cea-a3df-ea810d1daa42)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ruizemanuelm** [comment]
Buenas noches, pudimos solucionar los issues que nos dejaron en el
repositorio de github. Esperamos su respuesta
https://github.com/ruizemanuelm/proyectoFinal

https://github.com/ruizemanuelm/backend_proyectoFinal

https://huellitas-rolling.netlify.app

mongodb+srv://
***@***.***/huellitas

Administrador: ***@***.***
password: 1234567aB$

Integrantes:
Lucio Lazarte
Alejandro Sebastian Orosco
Emanuel Ruiz Villalobo

Desde ya muchas gracias.

**Comment by Nidev-lab** [comment]
Hola buenas! Estuve revisando las correcciones realizadas y encontré unas pequeñas modificaciones que hacer en el formulario de pago, se las cargo en otra issue.
