### ISSUE TITLE
Formulario de pago

### ISSUE THREAD

**Issue by Nidev-lab** [ruizemanuelm/proyectoFinal#72]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Quise contratar un plan.

## Resultado esperado

1. Que al ingresar los datos de pago no permita poner valores negativos ni tampoco números donde va el nombre.

2. Una vez colocado todos los datos solicitados para contratar el plan que un modal diga que se realizo la compra con exito o que el boton "Suscribirse" redireccione a una page 404.

## Resultado actual

1. Se pueden colocar valores negativos y números donde va el nombre.

2. Al colocar todos los datos para la compra o suscripción del plan  el boton "Suscribirse" no genera ninguna accion y muestra un error por consola.

## Captura
1
![image](https://github.com/ruizemanuelm/proyectoFinal/assets/53904695/54875586-ad69-4c47-a47b-c138c2c299c2)
2
![image](https://github.com/ruizemanuelm/proyectoFinal/assets/53904695/deb3a8d7-82b9-46ce-8a38-186491065f2d)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas! Todas las modificaciones realizadas están bien, a excepción del formulario de pago que encontré unas pequeñas modificaciones a realizar, les cargo esta issue y con esto ya terminaríamos chicos.

**Comment by ruizemanuelm** [comment]
Buenas noches! hicimos la última corrección que nos dejaron en el
repositorio de github.
https://github.com/ruizemanuelm/proyectoFinal

https://github.com/ruizemanuelm/backend_proyectoFinal

https://huellitas-rolling.netlify.app

mongodb+srv://
***@***.***/huellitas

Administrador: ***@***.***
password: 1234567aB$

Integrantes:
Lucio Lazarte
Alejandro Sebastian Orosco
Emanuel Ruiz Villalobo

Esperamos su respuesta. Desde ya muchas gracias.

**Comment by Nidev-lab** [comment]
Perfecto chicos! Ahí verifique que este todo ok. Felicidades!
